### ISSUE TITLE
Cropped version in original's srcset if original ratio == crop ratio

### ISSUE THREAD

**Issue by bikubi** [vollyimnetz/crop-thumbnails#16]
WordPress's [wp_calculate_image_srcset](https://developer.wordpress.org/reference/functions/wp_calculate_image_srcset/) [picks alternative resolutions by aspect ratio](http://wordpress.stackexchange.com/a/241906) _only_, it doesn't check if an image size is "cropped" or not (unlike this plugin!). Thus, it might pick up a cropped version if it has the same ratio as the source image. This is usually unnoticeable as WordPress's default "automatically maximized" crop yields the original image. If you use this plugin to crop a thumbnail, the cropped version might might end up in the image's srcset (which should obviously not contain it, images in srcset should only differ in resolution/size).

To reproduce:
1. add an image size: `add_image_size('crop', 400, 300, true);`
2. upload an image with the exact same ratio, say 1200x900px
3. crop it using the plugin
4. in the theme, insert it with `wp_get_attachment_image($id, 'crop');`
5. check HTML output; the `-400x300` version shows up in the `srcset`

Possible workarounds:
- ~~avoid images with certain aspect ratios~~ ;)
- try to filter files considered for srcsets by hooking into `wp_calculate_image_srcset_meta`; I tried this, but gave up due to complexity :|
- disable srcsets by calling `wp_get_attachment_image_src` explicitly :(

Who's bug is this?
- From this plugin's view this wasn't a bug before [srcsets landed in 4.4](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/)
- WordPress's current behaviour works, but is not logical IMO; plus it could safely skip cropped image sizes for srcsets.

**Comment by vollyimnetz** [comment]
hi @bikubi,
thanks for reporting. I will investigate the reasons behind it.

If a default (unchanged) cropped image-size appears in the srcset, then i will not change the behavior (cause then its a bug the wordpress-core team has to fix). But if the output in the srcset changes after the plugin croppes the image, then i will try to fix this.

**Comment by vollyimnetz** [comment]
hi @bikubi,
today i tested a little bit. That's my results:

## 1. srcset-output
I can't recognize any change in the srcset-output depending if a image is cropped or not. That means, the filenames are the same. (Except for one bug that will be fixed in the next major release and that will only occure if you are use sizes like :
```
add_image_size('dynamic-2',9999,500, true);
add_image_size('dynamic-zero-width',0,500, true);
```
).

Evaluation: Its a good sign, that the filenames inside srcset are the same. That means the plugin do not mess with the srcset (whether a file is manually cropped or not).

## 2. srcset mixes cropped image-sizes with uncropped image-sizes
As you described i also recognize the mix of cropped and uncropped image-sizes. 

Evaluation: As you mentioned, in theory this is a wordpress-core-problem, but in wordpress-core its not possible to change the crop. **So ... yeah, it should be handled by the plugin in some way.**

## Solution
I will have a look at `wp_calculate_image_srcset` and `wp_calculate_image_sizes` filters in the near future, to check if i can add an option for change the output of srcset to only show uncropped/cropped image sizes.


By the way, i do not think that srcset images should always contain same ratio and same content. General speaking, it depend on your intention as designer/programmer to add whatever image you want on a certain viewport size.
The main problem is, the user of this wordpress plugin do not expect a change in behavior depending of the size of the original image.
